2024-01-08 19:45:04,230  ERROR  Internal Server Error: /news/  C:\python3.11\Lib\site-packages\django\utils\log.py
Traceback (most recent call last):
  File "C:\python3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/post_list.html
2024-01-08 19:45:04,277  ERROR  "GET /news/ HTTP/1.1" 500 85431  C:\python3.11\Lib\site-packages\django\core\servers\basehttp.py

2024-01-09 17:18:22,575  ERROR  Internal Server Error: /news/  C:\python3.11\Lib\site-packages\django\utils\log.py
Traceback (most recent call last):
  File "C:\python3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/post_list.html
2024-01-09 17:18:25,168  ERROR  "GET /news/ HTTP/1.1" 500 85658  C:\python3.11\Lib\site-packages\django\core\servers\basehttp.py

2024-01-11 18:06:31,957  INFO  "GET / HTTP/1.1" 200 576  C:\python3.11\Lib\site-packages\django\core\servers\basehttp.py

2024-01-11 18:06:33,751  INFO  "GET /news/ HTTP/1.1" 200 13185  C:\python3.11\Lib\site-packages\django\core\servers\basehttp.py

2024-01-11 18:14:36,919  INFO  "GET /news/ HTTP/1.1" 200 13185  C:\python3.11\Lib\site-packages\django\core\servers\basehttp.py

2024-01-11 18:14:40,219  INFO  "GET /news/ HTTP/1.1" 200 13185  C:\python3.11\Lib\site-packages\django\core\servers\basehttp.py

2024-01-11 18:14:46,129  INFO  "GET / HTTP/1.1" 200 576  C:\python3.11\Lib\site-packages\django\core\servers\basehttp.py

2024-01-11 18:22:10,563  INFO  "GET / HTTP/1.1" 200 576  C:\python3.11\Lib\site-packages\django\core\servers\basehttp.py

2024-01-11 18:22:12,002  INFO  "GET /news/ HTTP/1.1" 200 13185  C:\python3.11\Lib\site-packages\django\core\servers\basehttp.py

2024-01-11 18:45:47,001  INFO  "GET /news/ HTTP/1.1" 200 13185  C:\python3.11\Lib\site-packages\django\core\servers\basehttp.py

2024-01-13 23:59:41,369  ERROR  Internal Server Error: /news/  C:\python3.11\Lib\site-packages\django\utils\log.py
Traceback (most recent call last):
  File "C:\python3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/post_list.html
2024-01-13 23:59:41,369  ERROR  "GET /news/ HTTP/1.1" 500 85521  C:\python3.11\Lib\site-packages\django\core\servers\basehttp.py

INFO 2024-01-15 21:12:13,407  "GET /categories/ HTTP/1.1" 200 3896  C:\python3.11\Lib\site-packages\django\core\servers\basehttp.py  None

INFO 2024-01-15 21:12:15,392  "GET /news/ HTTP/1.1" 200 12964  C:\python3.11\Lib\site-packages\django\core\servers\basehttp.py  None

ERROR 2024-01-17 00:13:17,952  Internal Server Error: /news/  C:\python3.11\Lib\site-packages\django\utils\log.py  (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('news/post_list.html'), <traceback object at 0x00000254141DA300>)
Traceback (most recent call last):
  File "C:\python3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/post_list.html
ERROR 2024-01-17 00:13:20,454  Internal Server Error: /news/  C:\python3.11\Lib\site-packages\django\utils\log.py  (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('news/post_list.html'), <traceback object at 0x000002541534B780>)
Traceback (most recent call last):
  File "C:\python3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python3.11\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/post_list.html
ERROR 2024-01-17 00:13:23,490  "GET /news/ HTTP/1.1" 500 145  C:\python3.11\Lib\site-packages\django\core\servers\basehttp.py  None

